import { LocationType } from './activity';
import { Herb } from './inventory.service';

// alphabetical list of weapons
export const WeaponNames = [
  'adze',
  'ahlspiess',
  'aikuchi',
  'aklys',
  'arbir',
  'arit',
  'aruval',
  'atgeir',
  'axe',
  'backsword',
  'bakatwa',
  'balisong',
  'bardiche',
  'barong',
  'baselard',
  'baton',
  'battle-axe',
  'bhuj',
  'bichuwa',
  'bilbo',
  'bill',
  'bisento',
  'bludgeon',
  'bokken',
  'bolo',
  'boomerang',
  'brandistock',
  'broadaxe',
  'bo',
  'cambuk',
  'cestus',
  'changdao',
  'chigiriki',
  'chokuto',
  'cinquedea',
  'claw',
  'claymore',
  'club',
  'colichemarde',
  'crop',
  'crowbill',
  'cumberjung',
  'cutlass',
  'dadao',
  'dagger',
  'dao',
  'doloire',
  'dory',
  'dotanuki',
  'dussack',
  'eku',
  'emeici',
  'estoc',
  'falcata',
  'falchion',
  'falx',
  'fan',
  'fauchard',
  'firangi',
  'flail',
  'flamberge',
  'flyssa',
  'fork',
  'fu',
  'gada',
  'gauntlet',
  'gladius',
  'glaive',
  'goad',
  'goedendag',
  'golok',
  'guan',
  'guisarme',
  'gurz',
  'hachiwara',
  'hakapik',
  'haladie',
  'halberd',
  'hammer',
  'handaxe',
  'harpe',
  'hasta',
  'hatchet',
  'hwando',
  'hwandudaedo',
  'ida',
  'iklwa',
  'jambiya',
  'jawbone',
  'ji',
  'jian',
  'jukjangchangbo',
  'jutte',
  'kaiken',
  'kalis',
  'kama',
  'kampilan',
  'karabela',
  'karambit',
  'kard',
  'kaskara',
  'kastane',
  'katana',
  'katar',
  'katzbalger',
  'kerala',
  'khanda',
  'khanjali',
  'khanjar',
  'khopesh',
  'kila',
  'kilij',
  'kirpan',
  'klewang',
  'knife',
  'knives',
  'knobkierrie',
  'ko',
  'kodachi',
  'kopis',
  'kora',
  'kotiate',
  'krabi',
  'kris',
  'kudi',
  'kujang',
  'kukri',
  'kurunthadi',
  'kusari-gama',
  'kyoketsu-shoge',
  'labrys',
  'lance',
  'lathi',
  'liuyedao',
  'longsword',
  'luwuk',
  'macana',
  'mace',
  'machete',
  'macuahuitl',
  'maduvu',
  'mallet',
  'mameluke',
  'man-catcher',
  'mandau',
  'manriki',
  'masakari',
  'mattock',
  'maul',
  'menavlion',
  'mere',
  'messer',
  'misericorde',
  'moplah',
  'morning-star',
  'morningstar',
  'mubuchae',
  'mughal',
  'naboot',
  'nagamaki',
  'naginata',
  'nair',
  'nandao',
  'ngao',
  'nihonto',
  'nimcha',
  'ninjato',
  'nodachi',
  'nulbjakchang',
  'nunchaku',
  'nyepel',
  'ono',
  'palstave',
  'panabas',
  'partisan',
  'pata',
  'patag',
  'patu',
  'piandao',
  'pichangatti',
  'pick',
  'pickaxe',
  'pike',
  'pinuti',
  'pitchfork',
  'planson',
  'pudao',
  'pulwar',
  'punyal',
  'qama',
  'qiang',
  'quarterstaff',
  'ranseur',
  'rapier',
  'romphea',
  'roundhead',
  'rungu',
  'saber',
  'sabre',
  'sagaris',
  'sai',
  'saif',
  'saingeom',
  'saintie',
  'sang',
  'sarissa',
  'sasumata',
  'scepter',
  'scimitar',
  'scythe',
  'seax',
  'shamshir',
  'shareeravadi',
  'shashka',
  'shestopyor',
  'shikomizue',
  'shillelagh',
  'shortsword',
  'shuckra',
  'sibat',
  'sickle',
  'sledgehammer',
  'sodegarami',
  'sovnya',
  'spade',
  'spadroon',
  'spatha',
  'spear',
  'spetum',
  'ssangsudo',
  'staff',
  'stick',
  'suburito',
  'surik',
  'surujin',
  'sword',
  'swordstaff',
  'szabla',
  'tabak-toyok',
  'tabarzin',
  'taiaha',
  'takoba',
  'talibon',
  'talwar',
  'tambo',
  'tanto',
  'tekkan',
  'tekko',
  'tekpi',
  'tepoztopilli',
  'tewhatewha',
  'tibetan',
  'tlaximaltepoztli',
  'tomahawk',
  'tonfa',
  'tongi',
  'trident',
  'trishula',
  'tsurugi',
  'ulfberht',
  'vechevoral',
  'vettukathi',
  'voulge',
  'waddy',
  'waki',
  'wheel',
  'wodao',
  'wrench',
  'xiphos',
  'yanmaodao',
  'yari',
  'yatagan',
  'yawara',
  'yoroi-do',
  'yubi-bo',
  'zanbato',
  'zhanmadao',
  'zhua',
  'zweihander',
];

export const ChestArmorNames = ['jacket', 'coat', 'breastplate', 'jerkin', 'hauberk', 'vest', 'tunic', 'chestguard'];

export const LegArmorNames = ['pants', 'greaves', 'shinguards', 'trousers', 'shorts', 'leggings', 'skirt'];

export const HelmetNames = ['helmet', 'helm', 'mask', 'faceguard', 'cap', 'hat', 'hood'];

export const ShoeNames = ['sandals', 'boots', 'shoes', 'footwear', 'slippers'];

// prefixes in increasing order of goodness
export const ItemPrefixes = [
  'atrocious',
  'awful',
  'dreadful',
  'cheap',
  'crummy',
  'lousy',
  'poor',
  'abominable',
  'rough',
  'sad',
  'gross',
  'stinking',
  'imperfect',
  'flimsy',
  'shoddy',
  'inferior',
  'bad',
  'junky',
  'unusual',
  'aberrant',
  'deviant',
  'careless',
  'cheesy',
  'crappy',
  'cruddy',
  'defective',
  'deficient',
  'abnormal',
  'dissatisfactory',
  'erroneous',
  'faulty',
  'grungy',
  'icky',
  'inadequate',
  'incorrect',
  'slipshod',
  'substandard',
  'unsatisfactory',
  'mediocre',
  'inconsistent',
  'anomalous',
  'atypical',
  'strange',
  'ordinary',
  'regular',
  'common',
  'fair',
  'moderate',
  'humdrum',
  'intermediate',
  'peculiar',
  'medium',
  'middling',
  'standard',
  'customary',
  'everyday',
  'passable',
  'so-so',
  'tolerable',
  'undistinguished',
  'unexceptional',
  'decent',
  'usual',
  'green',
  'blue',
  'red',
  'puce',
  'mauve',
  'scarlet',
  'purple',
  'acceptable',
  'excellent',
  'exceptional',
  'familiar',
  'favorable',
  'positive',
  'satisfactory',
  'satisfying',
  'nice',
  'congenial',
  'pleasing',
  'sneaky',
  'agreeable',
  'polished',
  'commendable',
  'great',
  'marvelous',
  'superb',
  'valuable',
  'wonderful',
  'boss',
  'choice',
  'prime',
  'radical',
  'superior',
  'worthy',
  'admirable',
  'deluxe',
  'first-class',
  'first-rate',
  'gnarly',
  'honorable',
  'neat',
  'uncommon',
  'precious',
  'reputable',
  'shipshape',
  'splendid',
  'stupendous',
  'eminent',
  'excellent',
  'tiptop',
  'odd',
  'big',
  'considerable',
  'enormous',
  'extreme',
  'huge',
  'immense',
  'notable',
  'strong',
  'tremendous',
  'vast',
  'fat',
  'husky',
  'large',
  'mammoth',
  'ample',
  'bulky',
  'extended',
  'rare',
  'lovely',
  'extensive',
  'feral',
  'howling',
  'extravagant',
  'gigantic',
  'grievous',
  'humongous',
  'inordinate',
  'jumbo',
  'lengthy',
  'long',
  'oversize',
  'malignant',
  'fantastic',
  'beautiful',
  'magical',
  'enchanted',
  'prodigious',
  'stupendous',
  'titanic',
  'towering',
  'colossal',
  'extraordinary',
  'noteworthy',
  'phenomenal',
  'remarkable',
  'singular',
  'special',
  'super',
  'unique',
  'unprecedented',
  'unimaginable',
  'unthinkable',
  'heavenly',
  'divine',
];

export const WeaponSuffixes = [
  'irritation',
  'annoyance',
  'embarassment',
  'confusion',
  'frostbite',
  'flames',
  'wounding',
  'crushing',
  'draining',
  'bloodthirst',
  'light',
  'darkness',
  'power',
  'blasting',
  'decimation',
  'destruction',
  'supremacy',
  'obliteration',
  'annihilation',
];

export const WeaponSuffixModifiers = [
  'weak',
  'boring',
  'partial',
  'limited',
  'adequate',
  'medium',
  'substantial',
  'blinding',
  'complete',
  'burning',
  'total',
  'explosive',
  'poisonous',
  'ethereal',
  'overwhelming',
  'incalculable',
  'unfathomable',
  'obliterating',
  'limitless',
  'infinite',
  'eternal',
  'supreme',
  'perfect',
];

export const ArmorSuffixes = [
  'comfort',
  'screening',
  'safety',
  'cover',
  'shelter',
  'protection',
  'happiness',
  'security',
  'defense',
  'light',
  'darkness',
  'immunity',
  'power',
  'inviolability',
  'supremacy',
  'invulnerability',
  'invincibility',
];

export const ArmorSuffixModifiers = [
  'weak',
  'scant',
  'boring',
  'limited',
  'partial',
  'adequate',
  'medium',
  'substantial',
  'complete',
  'total',
  'overwhelming',
  'incalculable',
  'unfathomable',
  'limitless',
  'infinite',
  'eternal',
  'supreme',
  'perfect',
];

export const Herbs: Herb[] = [
  {
    name: 'patchouli',
    attribute: 'toughness',
    locations: [LocationType.SmallTown, LocationType.Forest, LocationType.Jungle],
  },
  {
    name: 'alangium',
    attribute: 'speed',
    locations: [LocationType.Forest, LocationType.Jungle],
  },
  {
    name: 'lobelia',
    attribute: 'charisma',
    locations: [LocationType.SmallTown, LocationType.Forest],
  },
  {
    name: 'lovage',
    attribute: 'charisma',
    locations: [LocationType.Forest],
  },
  {
    name: 'anemone',
    attribute: 'intelligence',
    locations: [LocationType.Forest],
  },
  {
    name: 'kudzu',
    attribute: 'strength',
    locations: [LocationType.Forest, LocationType.SmallTown],
  },
  {
    name: 'marlberry',
    attribute: 'toughness',
    locations: [LocationType.Beach, LocationType.SmallPond],
  },
  {
    name: 'aster',
    attribute: 'toughness',
    locations: [LocationType.Forest, LocationType.SmallTown, LocationType.SmallPond],
  },
  {
    name: 'milkvetch',
    attribute: 'strength',
    locations: [LocationType.Desert],
  },
  {
    name: 'safflower',
    attribute: 'strength',
    locations: [LocationType.Desert],
  },
  {
    name: 'cinnamon',
    attribute: 'intelligence',
    locations: [LocationType.Jungle],
  },
  {
    name: 'velvetleaf',
    attribute: 'toughness',
    locations: [LocationType.Forest, LocationType.SmallTown],
  },
  {
    name: 'goldthread',
    attribute: 'charisma',
    locations: [LocationType.SmallPond, LocationType.Forest, LocationType.MountainTops],
  },
  {
    name: 'lilac',
    attribute: 'intelligence',
    locations: [LocationType.Forest, LocationType.SmallTown],
  },
  {
    name: 'jimson',
    attribute: 'speed',
    locations: [LocationType.SmallTown, LocationType.Forest],
  },
  {
    name: 'dendrobium',
    attribute: 'charisma',
    locations: [LocationType.Jungle, LocationType.MountainTops, LocationType.Forest],
  },
  {
    name: 'ephedra',
    attribute: 'speed',
    locations: [LocationType.Desert],
  },
  {
    name: 'forsythia',
    attribute: 'speed',
    locations: [LocationType.Forest, LocationType.LargeCity],
  },
  {
    name: 'honeylocust',
    attribute: 'toughness',
    locations: [LocationType.SmallPond, LocationType.Forest],
  },
  {
    name: 'licorice',
    attribute: 'strength',
    locations: [LocationType.SmallTown],
  },
  {
    name: 'holly',
    attribute: 'strength',
    locations: [LocationType.Forest],
  },
  {
    name: 'motherwort',
    attribute: 'charisma',
    locations: [LocationType.Forest, LocationType.SmallTown],
  },
  {
    name: 'arborvitae',
    attribute: 'intelligence',
    locations: [LocationType.SmallPond, LocationType.Forest],
  },
  {
    name: 'snakeroot',
    attribute: 'intelligence',
    locations: [LocationType.Forest],
  },
  {
    name: 'foxglove',
    attribute: 'toughness',
    locations: [LocationType.SmallTown],
  },
  {
    name: 'stringbush',
    attribute: 'charisma',
    locations: [LocationType.MountainTops],
  },
  {
    name: 'ginger',
    attribute: 'speed',
    locations: [LocationType.Forest, LocationType.Jungle],
  },
  {
    name: 'ginkgo',
    attribute: 'intelligence',
    locations: [LocationType.Forest, LocationType.SmallTown, LocationType.LargeCity, LocationType.Desert],
  },
  {
    name: 'ginseng',
    attribute: 'strength',
    locations: [LocationType.MountainTops, LocationType.Forest],
  },
];

export const herbQuality = [
  'rotten',
  'wilted',
  'tiny',
  'poor',
  'weak',
  'low-grade',
  'average',
  'healthy',
  'abundant',
  'quality',
  'great',
  'huge',
  'exceptional',
  'amazing',
  'exquisite',
  'sublime',
  'spiritual',
  'divine',
];
