export const JoinTheGodsText =
  'You take to the skies, soaring far above the human realms. Over the Kunlun mountains, past Mount Tai, and beyond the Jade Mountains, you find the great sea and finally the island where Mount Penglai stands tall, risiing up into the clouds. Above the pure white slopes, the mountain is crowned with a golden palace surrounded by an orchard of trees that grow the finest jewels and the most delectable fruits that grant perfect health and eternal youth to whoever eats them. Suddenly you feel a twinge of doubt. Your own peaches never looked so inviting, no matter how hard you worked your land to cultivate them.\n\n' +
  "You push down your feelings of inadequacy and press onward toward the gates of the golden palace. You are immortal now, after all. You have earned your place here. As you stride into the large courtyard, you find an assembly of gods there, seated on golden thrones. The eight immortals are there, each holding their artifact of power as they laugh raucously at each other's jokes. Nuwa and Fuxi, the great ancestors of humanity, sit idly chatting as the Queen Mother of the West exchanges quiet words with Caishen in his most fine of all silks. In the center of them all, Shangti, the Jade Emperor himself, sits on his elevated throne. As you approach, he claps his hands for silence. You were clearly expected.\n\n" +
  '"Ah. The young upstart who has caused so much trouble in the mortal realm has finally arrived."\n\n' +
  'The other gods greet you with nothing but steely stares. You nod in acknowledgement and take another step toward the thrones. You notice that one of them off to the side is empty. A place for you, perhaps?\n\n' +
  '"I suppose you feel you deserve a place here with us now, do you?" the Jade Emperor continues. "Fight a few monsters, improve yourself a bit, conquer a few of your fellow mortals, and suddenly you\'ve earned the right to call yourself a god, eh?"\n\n' +
  'You nod again, preparing to recount the long journey of cultivation and devotion that led you to this point, when a towering figure to your right cuts you off before you can begin.\n\n' +
  '"Nonsense!" the ominous voice thunders. "This upstart destroyed one of my best servants and commited uncountable sins for which no price has been paid."\n\n' +
  '"And what would you suggest be done with this new immortal, Lord Yama?" the Emperor asks. "This one clearly shows the necessary power, and has no shortage of determination. One way or another, sooner or later that empty throne will be filled."\n\n' +
  '"Let this one come to my domain," Lord Yama declares. "The eighteen hells will show whether they have the character fitting for a throne in the Penglai Palace."\n\n' +
  'The other gods look back and forth at each other for a moment. "That seems only fair," One of them says, a short, hairy man with horns growing from his head. "This new immortal still has much to learn, and much to atone for. Why, they don\'t even understand simple concepts like balancing their yin and yang. They may be ready one day for this company, but a few millenia in Yama\'s realm will do them good."\n\n' +
  'The other gods murmer and nod agreement. Shangti rises to his feet. "Your words are wise, as always Pan Gu. Let this one be cast down to the eighteen hells. If they can master yin and yang and prove their worth through the trials of Yama\'s realm, we will welcome them as part of our celestial court."\n\n' +
  'Before you can say a word of protest, The Jade emperor waves one hand and you find yourself in a vast, bare, circular stone room. The walls are broken by eighteen open gates, each one leading to a different world of pain and suffering.\n\n' +
  'It looks like you have a new challenge ahead: Escape this underworld and prove your worth to the gods.';
